# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
#  desc "Description of what the lane does"
#  lane :custom_lane do
#    # add actions here: https://docs.fastlane.tools/actions
#  end

desc "Run unit tests"
  lane :tests do
    run_tests(
      scheme: "Moments", 
      output_directory: "./fastlane/dist", 
      output_types: "html", 
      buildlog_path: "./fastlane/dist")
  end
  
  lane :code_lint do
    swiftlint(
      mode: :lint,
      executable: "Pods/SwiftLint/swiftlint",  # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
      raise_if_swiftlint_error: true)
  end

  lane :code_format do
    swiftlint(
      mode: :autocorrect,
      executable: "Pods/SwiftLint/swiftlint",  # The SwiftLint binary path (optional). Important if you've installed it via CocoaPods
      raise_if_swiftlint_error: true)
  end

  lane :sort_files do
    sh "../scripts/sort-Xcode-project-file.pl ../Moments/Moments.xcodeproj"
  end
end
